// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PictureAnimation","status":true,"description":"ピクチャのアニメーションプラグイン","parameters":{"最初のセルに戻る":"true"}},
{"name":"DTextPicture","status":true,"description":"動的文字列ピクチャ生成プラグイン","parameters":{}},
{"name":"PictureCallCommon","status":true,"description":"Clickable picture plugin","parameters":{"TransparentConsideration":"true","GameVariablePictureNum":"0","GameVariableTouchX":"0","GameVariableTouchY":"0","SuppressTouch":"false","AlwaysCommonInBattle":"false"}},
{"name":"TkoolMV_PluginCommandBook","status":true,"description":"プラグインコマンド集","parameters":{"制御文字の拡張":"いいえ","スクリプトに制御文字適用":"いいえ"}},
{"name":"WindowResize","status":true,"description":"ゲーム起動時のウィンドウサイズを変更します。","parameters":{"width":"624","height":"916"}},
{"name":"Yami_SkipTitle","status":true,"description":"Skip the title scene for testing purpose.","parameters":{}},
{"name":"Trb_LoadingAnimation","status":true,"description":"ローディング画面をアニメーションさせるプラグイン","parameters":{"コマ数":"3","再生速度":"10","x":"","y":""}},
{"name":"MoviePicture","status":true,"description":"MovieInScreenPlugin","parameters":{"MovieVolumeType":"none"}}
];
